# Generated by Django 2.1.4 on 2018-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181218_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='norm.jpg', upload_to='profile_pics'),
        ),
    ]
